# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-coffeescript]

# Permalinks
permalink:        pretty

# Setup
title:            dcastro blog
description:      'A stream of thoughts'
url:              http://www.diogocastro.com
baseurl:          /
blogurl:          /blog/
atomurl:          /blog/atom.xml

author:
  name:           'Diogo Castro'
  url:            http://www.diogocastro.com
  email:          dc@diogocastro.com

# Custom vars

github:
  comments_url:    https://api.github.com/repos/dcastro/dcastro.github.io/issues/<issue-id>/comments?per_page=100
  issue_url:       https://github.com/dcastro/dcastro.github.io/issues/<issue-id>


