# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            dcastro blog
tagline:          'A Jekyll theme'
description:      'A stream of thoughts'
url:              http://www.diogocastro.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
